services:
  - type: web
    name: gasto-comum-api
    env: java
    plan: free
    buildCommand: "./mvnw clean package -DskipTests"
    startCommand: "java -jar target/gasto-comum-0.0.1-SNAPSHOT.jar"
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: gasto-comum-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: gasto-comum-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: gasto-comum-db
          property: password
      - key: SPRING_DATASOURCE_DRIVER_CLASS_NAME
        value: "com.mysql.cj.jdbc.Driver"
      - key: SERVER_PORT
        value: ${PORT}
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRATION
        value: "3600" # 1 hora
      - key: JWT_REFRESH
        value: "604800" # 7 dias
      - key: GOOGLE_CLIENT_ID
        sync: false # você configura no painel do Render
      - key: GOOGLE_CLIENT_SECRET
        sync: false # você configura no painel do Render
      - key: FRONTEND_URL
        value: "https://meu-frontend.onrender.com"
      - key: CORS_ALLOWEDORIGIN
        value: "https://meu-frontend.onrender.com"
      - key: FILE_UPLOAD_DIRECTORY
        value: "/opt/render/project/src/file-storage"

databases:
  - name: gasto-comum-db
    plan: free
    databaseName: gastocomum_api
    user: admin
    ipAllowList: [] # libera acesso apenas para sua API
    mysqlVersion: 8
